#!/bin/sh

if test ! -e ../flipstone-cookbooks; then
  (cd .. && git clone git@github.com:flipstone/flipstone-cookbooks.git)
fi;

if test ! -e cookbooks; then
  ln -s ../flipstone-cookbooks/cookbooks .
fi;

if test ! -e roles; then
  ln -s ../flipstone-cookbooks/roles .
fi;
